### ISSUE TITLE
A user should be able to set up a computer to collect data for their library.

### ISSUE THREAD

**Issue by jadudm** [18F/imls-pi-stack#57]
**Background**

Users should be able to set up a device they own for data collection.

It covers the following stories:

1. As an ...

**We'll know we're done when...**
- [ ] When a user can visit a central host to register their device and FCSF.
- [ ] When a user can download an installer pre-configured w/ FCSF, UID, keys.
- [ ] When a user can install (as administrator)
- [ ] When a user can confirm heartbeat on central server.
  
**Tasks**
- [ ] Develop a webhook to launch the build process from Directus. (example task)
- [ ] Engineering engineers all the things

**Definition of Done**

- [ ] Meets technical definition of done
- [ ] Meets acceptance criteria
- [ ] PO approved
- [ ] Usability tested
- [ ] FE test suite updated to test the form
- [ ] API test suite updated to demonstrate functionality, correctness.
- [ ] Rough draft of support documentation ("exists" not "perfect").
